  version: '3.3'
    
  services:
    web:
      build:
         context: ./birras
         dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - CONTAINER=web
      depends_on:
        - redis
    redis:
        image: redis
    celery-worker:
        build: 
            context: ./birras
            dockerfile: Dockerfile
        environment:
          - CONTAINER=worker
        depends_on:
           - redis
           - web
    celery-flower:
        build: 
            context: ./birras
            dockerfile: Dockerfile
        ports:
          - "5555:5555"
        environment:
          - CONTAINER=flower
        depends_on:
           - redis
           - web
    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
        - 9090:9090
      command:
        - --config.file=/etc/prometheus/prometheus.yml
      volumes:
        - ./prometheus_yml/:/etc/prometheus/
    grafana:
      image: grafana/grafana:6.5.2
      ports:
         - 3060:3000
