version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
       - 9090:9090
  grafana:
    image: grafana/grafana:6.5.2
    ports:
       - 3060:3000
