# Generated by Django 3.1 on 2020-08-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_meeter_meetups'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meeters',
            field=models.ManyToManyField(to='app.Meeter'),
        ),
    ]
