# Generated by Django 3.1 on 2020-08-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_meetup_meeters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meeters',
            field=models.ManyToManyField(blank=True, to='app.Meeter'),
        ),
    ]
