# Generated by Django 3.1 on 2020-08-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200826_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
