# Generated by Django 3.1 on 2020-08-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200826_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
