# Generated by Django 3.1 on 2020-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_currenttemperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currenttemperature',
            old_name='time_temp',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='currenttemperature',
            name='feels_like',
            field=models.FloatField(default=0, verbose_name='Feels Like'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currenttemperature',
            name='temp_max',
            field=models.FloatField(default=0, verbose_name='Max Temperature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currenttemperature',
            name='temp_min',
            field=models.FloatField(default=0, verbose_name='Min Temperature'),
            preserve_default=False,
        ),
    ]
