# Generated by Django 3.1 on 2020-08-31 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200827_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinMeetUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeter', models.ManyToManyField(to='app.Meeter')),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.meetup')),
            ],
        ),
    ]
