# Generated by Django 3.1 on 2020-08-31 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_meetup_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinmeetup',
            name='meeter',
        ),
    ]
