# Generated by Django 3.1 on 2020-08-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_checkinmeetup_meeter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinmeetup',
            name='meetup',
        ),
    ]
