# Generated by Django 3.1 on 2020-08-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_checkinmeetup_meetup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckinMeetUp',
        ),
    ]
